--[[
Command Configs
/reload monster
/reload shop
etc...
]]--
RELOAD_SWITCH = 0
RELOAD_COMMAND_SYNTAX = '/reload'
REALOD_GAME_MASTER_LEVEL = 1
RELOAD_COMMAND_MONSTER = 'monster'
RELOAD_COMMAND_ITEM = 'item'
RELOAD_COMMAND_CUSTOM = 'custom'
RELOAD_COMMAND_CHARACTER = 'character'
RELOAD_COMMAND_UTIL = 'util'
RELOAD_COMMAND_EVENT = 'event'
RELOAD_COMMAND_EVENTITEMBAG = 'eventitembag'
RELOAD_COMMAND_SKILL = 'skill'
RELOAD_COMMAND_HACK = 'hack'
RELOAD_COMMAND_COMMON = 'common'
RELOAD_COMMAND_MIX = 'mix'
RELOAD_COMMAND_SHOP = 'shop'
RELOAD_COMMAND_CASHSHOP = 'cashshop'
RELOAD_COMMAND_MOVE = 'move'
RELOAD_COMMAND_QUEST = 'quest'
RELOAD_COMMAND_LUA = 'lua'